json.call(
  account.decorate,
  :email,
  :managed_account_id,
  :first_name,
  :last_name,
  :nickname,
  :image_url,
  :country,
  :date_of_birth,
  :verification_state,
  :verification_date,
  :verification_max_investment_usd,
  :created_at,
  :updated_at
)
